export const weatherIcons:any = {
    'Sunny': require('../assets/images/weatherIcons/sunny.png'),
    'Clear': require('../assets/images/weatherIcons/clear.png'),
    'Partly Cloudy': require('../assets/images/weatherIcons/partly_cloudy.png'),
    'Cloudy': require('../assets/images/weatherIcons/cloudy.png'),
    'Overcast': require('../assets/images/weatherIcons/overcast.png'),
    'Mist': require('../assets/images/weatherIcons/mist.png'),
    'Patchy rain nearby': require('../assets/images/weatherIcons/patchy_rain_possible.png'),
    'Patchy snow nearby': require('../assets/images/weatherIcons/patchy_snow_possible.png'),
    'Patchy sleet nearby': require('../assets/images/weatherIcons/patchy_sleet_possible.png'),
    'Patchy freezing drizzle nearby': require('../assets/images/weatherIcons/patchy_freezing_drizzle_possible.png'),
    'Thundery outbreaks nearby': require('../assets/images/weatherIcons/thundery_outbreaks_possible.png'),
    'Patchy rain possible': require('../assets/images/weatherIcons/patchy_rain_possible.png'),
    'Patchy snow possible': require('../assets/images/weatherIcons/patchy_snow_possible.png'),
    'Patchy sleet possible': require('../assets/images/weatherIcons/patchy_sleet_possible.png'),
    'Patchy freezing drizzle possible': require('../assets/images/weatherIcons/patchy_freezing_drizzle_possible.png'),
    'Thundery outbreaks possible': require('../assets/images/weatherIcons/thundery_outbreaks_possible.png'),
    'Blowing snow': require('../assets/images/weatherIcons/blowing_snow.png'),
    'Blizzard': require('../assets/images/weatherIcons/blizzard.png'),
    'Fog': require('../assets/images/weatherIcons/fog.png'),
    'Freezing fog': require('../assets/images/weatherIcons/freezing_fog.png'),
    'Patchy light drizzle': require('../assets/images/weatherIcons/patchy_light_drizzle.png'),
    'Light drizzle': require('../assets/images/weatherIcons/light_drizzle.png'),
    'Freezing drizzle': require('../assets/images/weatherIcons/freezing_drizzle.png'),
    'Heavy freezing drizzle': require('../assets/images/weatherIcons/heavy_freezing_drizzle.png'),
    'Patchy light rain': require('../assets/images/weatherIcons/patchy_light_rain.png'),
    'Light rain': require('../assets/images/weatherIcons/light_rain.png'),
    'Moderate rain at times': require('../assets/images/weatherIcons/moderate_rain_at_times.png'),
    'Moderate rain': require('../assets/images/weatherIcons/moderate_rain.png'),
    'Heavy rain at times': require('../assets/images/weatherIcons/heavy_rain_at_times.png'),
    'Heavy rain': require('../assets/images/weatherIcons/heavy_rain.png'),
    'Light freezing rain': require('../assets/images/weatherIcons/light_freezing_rain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/weatherIcons/moderate_or_heavy_freezing_rain.png'),
    'Light sleet': require('../assets/images/weatherIcons/light_sleet.png'),
    'Moderate or heavy sleet': require('../assets/images/weatherIcons/moderate_or_heavy_sleet.png'),
    'Patchy light snow': require('../assets/images/weatherIcons/patchy_light_snow.png'),
    'Light snow': require('../assets/images/weatherIcons/light_snow.png'),
    'Patchy moderate snow': require('../assets/images/weatherIcons/patchy_moderate_snow.png'),
    'Moderate snow': require('../assets/images/weatherIcons/moderate_snow.png'),
    'Patchy heavy snow': require('../assets/images/weatherIcons/patchy_heavy_snow.png'),
    'Heavy snow': require('../assets/images/weatherIcons/heavy_snow.png'),
    'Ice pellets': require('../assets/images/weatherIcons/ice_pellets.png'),
    'Light rain shower': require('../assets/images/weatherIcons/light_rain_shower.png'),
    'Moderate or heavy rain shower': require('../assets/images/weatherIcons/moderate_or_heavy_rain_shower.png'),
    'Torrential rain shower': require('../assets/images/weatherIcons/torrential_rain_shower.png'),
    'Light sleet showers': require('../assets/images/weatherIcons/light_sleet_showers.png'),
    'Moderate or heavy sleet showers': require('../assets/images/weatherIcons/moderate_or_heavy_sleet_showers.png'),
    'Light snow showers': require('../assets/images/weatherIcons/light_snow_showers.png'),
    'Moderate or heavy snow showers': require('../assets/images/weatherIcons/moderate_or_heavy_snow_showers.png'),
    'Light showers of ice pellets': require('../assets/images/weatherIcons/light_showers_of_ice_pellets.png'),
    'Moderate or heavy showers of ice pellets': require('../assets/images/weatherIcons/moderate_or_heavy_showers_of_ice_pellets.png'),
    'Patchy light rain with thunder': require('../assets/images/weatherIcons/patchy_light_rain_with_thunder.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/weatherIcons/moderate_or_heavy_rain_with_thunder.png'),
    'Patchy light snow with thunder': require('../assets/images/weatherIcons/patchy_light_snow_with_thunder.png'),
    'Moderate or heavy snow with thunder': require('../assets/images/weatherIcons/moderate_or_heavy_snow_with_thunder.png'),
}
