export const weatherTips:any = {
    'Sunny': "It's a great day to be outdoors! Don't forget your sunscreen.",
    'Clear': "Enjoy the clear skies! Perfect for a walk or a bike ride.",
    'Partly Cloudy': "It's okay to hang out with your friends!",
    'Partly cloudy': "It's okay to hang out with your friends!",
    'partly cloudy': "It's okay to hang out with your friends!",
    'Cloudy': "It might be a bit gloomy, but it's a great day for indoor activities.",
    'Overcast': "Perfect weather for reading a book or watching a movie indoors.",
    'Mist': "Drive carefully and use your fog lights.",
    'Patchy rain nearby': "Keep an umbrella handy just in case.",
    'Patchy snow nearby': "Dress warmly and be cautious on the roads.",
    'Patchy sleet nearby': "Watch out for slippery surfaces and dress in layers.",
    'Patchy freezing drizzle nearby': "Be cautious of icy patches on roads and sidewalks.",
    'Thundery outbreaks nearby': "Stay indoors and avoid tall objects if you hear thunder.",
    'Blowing snow': "Limit travel and keep warm indoors.",
    'Blizzard': "Stay indoors and avoid travel if possible.",
    'Fog': "Drive slowly and use fog lights. Visibility is low.",
    'Freezing fog': "Be extra cautious on the roads. Visibility is poor and roads may be icy.",
    'Patchy light drizzle': "A light jacket and an umbrella should suffice.",
    'Light drizzle': "Carry an umbrella and wear waterproof shoes.",
    'Freezing drizzle': "Be cautious of ice accumulation on surfaces.",
    'Heavy freezing drizzle': "Stay indoors if possible. Roads and walkways will be very slippery.",
    'Patchy light rain': "Keep an umbrella with you just in case.",
    'Light rain': "A raincoat and umbrella are recommended.",
    'Moderate rain at times': "Expect intermittent rain showers. Stay dry!",
    'Moderate rain': "A good day to stay indoors and enjoy a hot drink.",
    'Heavy rain at times': "Heavy rain is possible. Plan indoor activities.",
    'Heavy rain': "Avoid going out if possible. Streets might flood.",
    'Light freezing rain': "Be cautious of icy roads and walkways.",
    'Moderate or heavy freezing rain': "Stay indoors if possible. Roads will be treacherous.",
    'Light sleet': "Watch your step outside and drive carefully.",
    'Moderate or heavy sleet': "Limit outdoor activities and travel.",
    'Patchy light snow': "A light snowfall. Perfect for a winter walk.",
    'Light snow': "Enjoy the snow, but dress warmly.",
    'Patchy moderate snow': "Snow is accumulating. Drive carefully and stay warm.",
    'Moderate snow': "A good day for building a snowman or staying cozy indoors.",
    'Patchy heavy snow': "Expect heavy snowfall in some areas. Travel carefully.",
    'Heavy snow': "Limit travel and enjoy the snowy scenery from indoors.",
    'Ice pellets': "Be cautious of slippery surfaces and falling ice pellets.",
    'Light rain shower': "A quick shower. Keep an umbrella handy.",
    'Moderate or heavy rain shower': "Expect heavy showers. Stay dry!",
    'Torrential rain shower': "Avoid going out if possible. Streets might flood quickly.",
    'Light sleet showers': "Be cautious of slippery surfaces and light sleet showers.",
    'Moderate or heavy sleet showers': "Stay indoors if possible. Sleet showers can be hazardous.",
    'Light snow showers': "A light snow shower. Enjoy the winter weather!",
    'Moderate or heavy snow showers': "Expect heavy snow showers. Limit travel and stay warm.",
    'Light showers of ice pellets': "Watch out for slippery surfaces and falling ice pellets.",
    'Moderate or heavy showers of ice pellets': "Stay indoors if possible. Ice pellets can be hazardous.",
    'Patchy light rain with thunder': "Stay indoors and avoid tall objects if you hear thunder.",
    'Moderate or heavy rain with thunder': "Thunderstorms expected. Stay indoors and stay safe.",
    'Patchy light snow with thunder': "Snow and thunder are rare. Stay indoors and enjoy the show.",
    'Moderate or heavy snow with thunder': "A rare occurrence. Stay indoors and stay safe."
};
